// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DA.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DA.Models
{
    public partial class HangfirePOCContext
    {
        private IHangfirePOCContextProcedures _procedures;

        public virtual IHangfirePOCContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new HangfirePOCContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IHangfirePOCContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class HangfirePOCContextProcedures : IHangfirePOCContextProcedures
    {
        private readonly HangfirePOCContext _context;

        public HangfirePOCContextProcedures(HangfirePOCContext context)
        {
            _context = context;
        }

        public virtual async Task<List<TestStordResult>> TestStordAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<TestStordResult>("EXEC @returnValue = [dbo].[TestStord]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
