// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DA.Models
{
    public partial class TestStordResult
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int DurationInSecound { get; set; }
        public string Description { get; set; }
        public DateTime LastRunUTC { get; set; }
        public DateTime NextRunUTC { get; set; }
        public int StopById { get; set; }
        public int RunById { get; set; }
    }
}
